### ISSUE TITLE
Butlerd Http API is Deprecated

### ISSUE THREAD

**Issue by titaniumtraveler** [nicohman/butlerd-rs#1]
Butlerd has stopped supporting the old HTTP protocol and now uses
json-rpc via raw TCP-Sockets. See [here](https://docs.itch.ovh/butlerd/master/#/?id=json-rpc-20-over-tcp).

Therefore it might be a good idea to explicitly mark this crate as depreciated to prevent confusion for new users.
I'm currently working on an implementation of the new protocol using `async` and `tokio`, but that's still very work-in-progress.

**Comment by nicohman** [comment]
Ok, thanks for letting me know!
